/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    getByName("main") {
        java.srcDirs(listOf("src/main/java"))
    }
}

application {
    // Default main class
    mainClass = "example.Deadlock"
}

tasks.named<JavaExec>("run") {
    // Allow overriding the main class via -PmainClass=<fully.qualified.ClassName>
    mainClass.set(project.findProperty("mainClass") as String? ?: application.mainClass.get())
}
