run-deadlock:
    ./gradlew :deadlock:run -PmainClass=example.Deadlock

run-phil-deadlock:
    ./gradlew :dining-philosophers:run -PmainClass=solution.DeadlockPhilosophers

run-phil:
    ./gradlew :dining-philosophers:run -PmainClass=solution.SafePhilosophers

run-ordering:
    ./gradlew :deadlock:run -PmainClass=example.ResourceOrdering

test:
    ./gradlew clean test

run-matrix *args:
    ./gradlew :matrix-multiplication:run --args="{{args}}"
